apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: daemonset-example
spec:
  containers:
    - name: pod
      image: alpine
      command:
        - "/bin/sh"
        - "-c"
        - "apk add --no-cache curl bash && sleep 60m"
      resources:
        limits:
          memory: 500Mi
          cpu: 10m
        requests:
          cpu: 10m
          memory: 100Mi
